// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/thumbnail": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Gera um thumbnail a partir de um HTML",
                "parameters": [
                    {
                        "description": "Parâmetros",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ThumbnailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ThumbnailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ThumbnailResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ThumbnailRequest": {
            "description": "Parâmetros para geração de thumbnail",
            "type": "object",
            "properties": {
                "base64": {
                    "type": "boolean"
                },
                "fullPage": {
                    "description": "Capturar a página inteira (true) ou apenas a viewport (false)",
                    "type": "boolean"
                },
                "headless": {
                    "type": "boolean"
                },
                "height": {
                    "type": "integer"
                },
                "htmlPath": {
                    "type": "string"
                },
                "quality": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "waitTime": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "main.ThumbnailResponse": {
            "description": "Resposta da geração de thumbnail",
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Thumbnail API",
	Description:      "Resposta da geração de thumbnail",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
